# Autogenerated by devscripts/update-version.py

__version__ = '2025.04.28'

RELEASE_GIT_HEAD = '5325b18e0c77f6d9bc34d2a593dc700d0a6897aa'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'sosumecho/yt-dlp'

ORIGIN = 'sosumecho/yt-dlp'

_pkg_version = '2025.04.28'
