# Autogenerated by devscripts/update-version.py

__version__ = '2025.03.19.033058'

RELEASE_GIT_HEAD = '2ee3a0aff9be2be3bea60640d3d8a0febaf0acb6'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'sosumecho/yt-dlp'

ORIGIN = 'sosumecho/yt-dlp'

_pkg_version = '2025.03.19.033058'
