# Autogenerated by devscripts/update-version.py

__version__ = '2025.05.16.025618'

RELEASE_GIT_HEAD = '99e3a0e0ad2c1efeec1ee2fa8e3a98b3a28bebcc'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'sosumecho/yt-dlp'

ORIGIN = 'sosumecho/yt-dlp'

_pkg_version = '2025.05.16.025618'
